spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=Etc/GMT-0
    username: root
    password: escheduler

  resources:
    chain:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb

  thymeleaf:
    cache: false

server:
  servlet:
    session:
      timeout: 60m
  port: 8080
